version: '3.8'

services:
  php:
    build:
      context: ./pruebaTecnica
      dockerfile: Dockerfile
    container_name: php_container
    environment:
      DB_DRIVER: pdo_mysql
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: pruebaTecnicaPHP
      DB_PORT: 3306
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pruebaTecnicaPHP
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: